/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#fef7ff",
        "on-tertiary-container": "#fffbff",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#c3c0ff",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#cac5c5",
        "on-secondary-fixed": "#110760",
        "surface-tint": "#2b6c1d",
        "on-error-container": "#93000a",
        "on-background": "#1d1a22",
        "secondary-fixed": "#e2dfff",
        "on-surface": "#1d1a22",
        "inverse-primary": "#91d87b",
        secondary: "#5755a5",
        "on-tertiary-fixed-variant": "#494646",
        "surface-container-low": "#f9f1fd",
        "surface-variant": "#e7e0eb",
        "surface-dim": "#dfd7e3",
        outline: "#717a6b",
        "on-primary-container": "#f8ffef",
        "surface-bright": "#fef7ff",
        "inverse-on-surface": "#f6eefa",
        "on-secondary-fixed-variant": "#3f3d8c",
        "on-primary": "#ffffff",
        "surface-container": "#f3ebf7",
        background: "#fef7ff",
        error: "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e7e0eb",
        "on-secondary-container": "#3c3988",
        "on-primary-fixed": "#022100",
        "on-primary-fixed-variant": "#0e5303",
        "primary-fixed": "#adf595",
        "error-container": "#ffdad6",
        "primary-container": "#428332",
        "primary-fixed-dim": "#91d87b",
        tertiary: "#5e5b5b",
        "outline-variant": "#c1c9b8",
        "surface-container-high": "#ede6f1",
        primary: "#28691a",
        "inverse-surface": "#322f37",
        "tertiary-fixed": "#e7e1e1",
        "secondary-container": "#aaa8ff",
        "on-error": "#ffffff",
        "tertiary-container": "#777474",
        "on-tertiary-fixed": "#1d1b1b",
        "on-surface-variant": "#41493c",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "4xl": "2rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["var(--font-inter)", "Inter", "-apple-system", "sans-serif"],
        body: ["var(--font-inter)", "Inter", "-apple-system", "sans-serif"],
        label: ["var(--font-inter)", "Inter", "-apple-system", "sans-serif"],
      },
      animation: {
        float: "floating 4s ease-in-out infinite",
        "fade-up": "fadeUp 0.7s ease-out both",
        "slide-down": "slideDown 0.3s ease-out both",
      },
      keyframes: {
        floating: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-12px)" },
        },
        fadeUp: {
          from: { opacity: 0, transform: "translateY(24px)" },
          to: { opacity: 1, transform: "translateY(0)" },
        },
        slideDown: {
          from: { opacity: 0, transform: "translateY(-8px)" },
          to: { opacity: 1, transform: "translateY(0)" },
        },
      },
    },
  },
  plugins: [],
};
